### ISSUE TITLE
verbosity option doesn't seem to affect the run

### ISSUE THREAD

**Issue by lguy** [gem-pasteur/macsyfinder#13]
Hi,
I tried to run macsyfinder with -vv, -vvv, --verbosity, but that doesn't alter the output. The .conf file that is output at the end of the run always show log_level = 30, irrespective of the option.
On the other hand, running with a .conf file where log_level is altered works. 

Running macyfinder up-to-date (commit 90e5b3ab8bc12c40790bab2908baa277a923808a)

**Comment by saphia** [comment]
Dear Lionel, 

Thank you, we will look into this! 

Best, 

Sophie
