### ISSUE TITLE
Gene column in the .report file

### ISSUE THREAD

**Issue by lguy** [gem-pasteur/macsyfinder#14]
Hi,
I'm running macsyfinder to identify T4SS in Legionella pneumophila. I'm using the TXSS profiles available from gem-pasteur as well. For example, when I'm running the pT4SSi model [https://github.com/gem-pasteur/Macsyfinder_models/blob/master/Data/TXSS/DEF/pT4SSi.xml](url) it refers (for 3 genes) to another model, CONJ, which has 'homologs' defined for two of these genes, T4SS_virb4 and T4SS_t4cp1
```
<system inter_gene_max_space="30" min_mandatory_genes_required="2" min_genes_required="3">  
	<gene name="T4SS_virb4" presence="mandatory" exchangeable="1">       
    	<homologs>
            <gene name="T4SS_I_traU"/>
        </homologs>
    </gene>
    <gene name="T4SS_t4cp1" presence="mandatory" exchangeable="1">      
        <homologs>
            <gene name="T4SS_tcpA"/>
            <gene name="T4SS_t4cp2"/>
        </homologs>

    </gene>
</pre>
```
For some reason, the .summary file lists the original gene names (e.g. T4SS_virb4, T4SS_t4cp1) but the .report file uses the name of the homologs in CONJ.xml (T4SS_I_traU, T4SS_t4cp2).

If I understand correctly, the gene_name of the original definition file defines the "function", whereas the actual .xml profile of whichever homolog matched best gives the "match", but this is not very transparent and makes it a bit confusing, comparing the summary and the report file. I would find it very useful to have two columns in the report file ("function" and "match", instead of a single "gene"), reflecting the terminology used in the .json file.

**Comment by saphia** [comment]
Dear Lionel, 

Yes you're right, there is some kind of inconsistency here, we will fix this to have the information about both the 'match' and the 'function' in the .report file.
