### ISSUE TITLE
Test occurs problems

### ISSUE THREAD

**Issue by HaidYi** [gem-pasteur/macsyfinder#17]
Hi maintainer,
I am wondering why it occurs:

My environment is:  ubuntu 15.10 python2.7.
My command is: python2 setup.py test -vv

Here are the Ouputs from program with err:

running functional tests
test_basic_run (test_first_test.Test) ... FAIL

======================================================================
FAIL: test_basic_run (test_first_test.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/haidong/PycharmProjects/macsyfinder-master/tests/functional/test_first_test.py", line 95, in test_basic_run
    command))
AssertionError: macsyfinder finished with non zero exit code: 1 command launched=
/home/haidong/PycharmProjects/macsyfinder-master/bin/macsyfinder --def=/home/haidong/PycharmProjects/macsyfinder-master/tests/data/data_set_1/def --profile-dir=/home/haidong/PycharmProjects/macsyfinder-master/tests/data/data_set_1/profiles --out-dir=/tmp/macsyfinder_test_basic_run --sequence-db=/home/haidong/PycharmProjects/macsyfinder-master/tests/data/base/test_aesu.fa --db-type=gembase T9SS T3SS T4SS_typeI

----------------------------------------------------------------------
Ran 1 test in 0.049s

FAILED (failures=1)

**Comment by HaidYi** [comment]
I am looking forward to your response.

**Comment by bneron** [comment]
can you run the following command and send us the complete trace back:
```
/home/haidong/PycharmProjects/macsyfinder-master/bin/macsyfinder --def=/home/haidong/PycharmProjects/macsyfinder-master/tests/data/data_set_1/def --profile-dir=/home/haidong/PycharmProjects/macsyfinder-master/tests/data/data_set_1/profiles --out-dir=/tmp/macsyfinder_test_basic_run --sequence-db=/home/haidong/PycharmProjects/macsyfinder-master/tests/data/base/test_aesu.fa --db-type=gembase T9SS T3SS T4SS_typeI
```

**Comment by HaidYi** [comment]
Yes, I have tried the command you wrote but the ploblem occurs:
Cannot import macsypy, check your installation or your MACSY_HOME variable : No module named 'macsypy'

**Comment by bneron** [comment]
do you want to use macsyfinder or add new feature to macsyfinder?
If you intended to use only macsyfinder please install macsyfinder from the distribution not from the repository.

**Comment by HaidYi** [comment]
Thank you.

**Comment by HaidYi** [comment]
I use this command in ubuntu to install macsyfinder
```
sudo apt-get install macsyfinder
```
And then I use 
```
macsyfinder -h
```
to test whether I have installed it correctly. It can get the correct output.
But when I use this command to do some analysis, 
```
macsyfinder --db-type gembase --sequence-db NC_008818.1.fasta all
``` 
It occurs this traceback
```
Traceback (most recent call last):
  File "/usr/bin/macsyfinder", line 286, in <module>
    worker_nb = args.worker_nb
  File "/usr/lib/python2.7/dist-packages/macsypy/config.py", line 180, in __init__
    self.options = self._validate(cmde_line_opt, values)
  File "/usr/lib/python2.7/dist-packages/macsypy/config.py", line 588, in _validate
    raise err
ValueError: debian/macsyfinder/usr/share/macsyfinder/DEF: No such definition directory
```

Looking forward to your reply. Thank you.
