### ISSUE TITLE
Other system modules

### ISSUE THREAD

**Issue by sarah872** [gem-pasteur/macsyfinder#20]
I would like to download the modules `CapsuleDB` and `Secreton` - where can I find them?

**Comment by cachapuz2001** [comment]
You can find the modules to identify:
- capsules in https://gitlab.pasteur.fr/gem/capsuledb
- protein secretion systems (TXSScan) in https://github.com/gem-pasteur/Macsyfinder_models
Note that CapsuleDB and Secreton are databases with results, not the modules themselves.

**Comment by sarah872** [comment]
Are the modules also covering fimbriae?

**Comment by cachapuz2001** [comment]
Not yet (and that won't arrive in the next few months). See our Scientific Reports paper to see what we cover so far.
