### ISSUE TITLE
Please port to Python3

### ISSUE THREAD

**Issue by tillea** [gem-pasteur/macsyfinder#21]
Hello,
the Debian Med team is maintaining macsyfinder for official Debian. The recently released Debian 10 was the last Debian release featuring Python2 since this programming language is EOL. If you are interested that we continue to maintain macsyfinder in official Debian (and that users of other modern distributions will have no problems to install macsyfinder on their systems) I'd recommend you port your code to Python3. The 2to3 tool might be of great help here.
Kind regards, Andreas.

**Comment by bneron** [comment]
We are currently developing a new macsyfinder version  with lot of new features. 
Of course this version is running python3.

regards,

Bertrand

**Comment by tillea** [comment]
Hi Bertrand,
On Mon, Aug 05, 2019 at 12:37:18AM -0700, Bertrand Néron wrote:
> We are currently developing a new macsyfinder version  with lot of new features. 
> Of course this version is running python3.
Thanks for the prompt reply and the good news.  Regarding the workflow I would have prefered if you would have closed that issue after the said version is released.  This would have me informed about the availablility of a solution of the reported problem.  So please be so kind to drop me a note if you consider it more sensible to close the issue right now.
Kind regards, Andreas.
