### ISSUE TITLE
Macsyfinder installation problem

### ISSUE THREAD

**Issue by edusoto** [gem-pasteur/macsyfinder#22]
After successful 'python setup.py test -vv' (installation testing) I tried to install it using 'sudo python setup.py install' but I get the following error: 

sudo python setup.py install
running install
error: [Errno 2] No such file or directory: 'build/lib.linux-x86_64-2.7/macsypy/config.py'

I would really appreciate any assistance.

Thanks in advance!

Eduardo

**Comment by bneron** [comment]
Hi Eduardo,

can you tell me, which linux distro and python version you use?

regards

**Comment by edusoto** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

Python 2.7.12

**Comment by bneron** [comment]
It's weird I just try to install on same os and it worked (see install commands below)
can you tell me what do you have in the `build` directory?
do you execute `python setup.py build` before the install phase? 

```bash
apt-get -y update
apt-get -y upgrade
apt-get -y install python
apt-get -y install wget
wget -O macsyfinder-1.0.5.tar.gz https://bintray.com/gem-pasteur/MacSyFinder/download_file?file_path=macsyfinder-1.0.5.tar.gz
tar -xzf macsyfinder-1.0.5.tar.gz 
cd macsyfinder-1.0.5
python setup.py build
python setup.py test -vv
python setup.py install
cd
macsyfinder --help
```

**Comment by edusoto** [comment]
Issue solved, it works! Thanks again!
