### ISSUE TITLE
No module named 'ConfigParser'

### ISSUE THREAD

**Issue by YanpingHu** [gem-pasteur/macsyfinder#25]
I have a problem when I'm installing it.
Cannot import macsypy, check your installation or your MACSY_HOME variable : No module named 'ConfigParser'
I hope you help me solve it.Thanks!

**Comment by bneron** [comment]
This because you use a developer version,
If you want to use macsyfinder please download the distribution (click on the bue button download macsyfinder) and follow the instructions.
