### ISSUE TITLE
Input sequence

### ISSUE THREAD

**Issue by liangcmu** [gem-pasteur/macsyfinder#31]
Dear developers:

I have a few questions about the required input for MacSyFinder.  
(1) It will not accept genome DNA sequence. Right?
(2) For a sequenced genome of one bacterium, we want to detect potential Cas genes using MacSyFinder.  Should I do 6 frame translation of whole DNA sequences and then use these amino acids as the input for detection?  Otherwise, should I use the predicted genes and relevant CDS (amino acids) from the gene annotation as the inputs?  Any comment or suggestion will be highly appreciated!

**Comment by cachapuz2001** [comment]
Hi,
(1) exactly. it only accepts proteins sequences.
(2) As you want. But providing the annotated proteins seems simpler and better. You can use RAST, Prokka or DFAST to annotate them (if annotation not available already).
