### ISSUE TITLE
Proper input format

### ISSUE THREAD

**Issue by liangcmu** [gem-pasteur/macsyfinder#32]
We want to examine the potential CAS proteins in all archaea genomes. We have already obtained translated CDS protein sequences for each genome.  Then, we aggregated all amino acid sequences from all the genomes to form a single sequence file in FASTA format: archaea.faa. 

We have tried two different input format:

(1) macsyfinder --db-type gembase --sequence-db all_archaea.faa -w 70 all
(2) macsyfinder --db-type ordered_replicon --replicon-topology linear -w 70 --sequence-db all_archaea.faa all

These two commands give us very different results.  So, which one is more appropriate?  For the (2), we can get summary results within a single file. For the (1), we do not have single summary result, but have a lot of individual result files.  For downstream bioinformatics analysis, (2) seems to be better (e.g. easy parsing).  What is your suggestion for this? 
Thank you very much in advance for your help!

**Comment by cachapuz2001** [comment]
Please read the manual to understand the differences between the two. The gembase is a special format. If you have not followed the conventions, your results will be meaningless.
