### ISSUE TITLE
conda installation?

### ISSUE THREAD

**Issue by cschu** [gem-pasteur/macsyfinder#33]
Hi, are you planning to add this to bioconda or another conda channel? If so, do you have any estimate when that would happen?

Thanks,
Christian

**Comment by bneron** [comment]
yes, we plan to add macsyfinder in bioconda and provide docker container as soon we have the definitive 2.0 version

bertrand

**Comment by cschu** [comment]
Sounds great, thanks! Do you have any ballpark estimate regarding the timeline?

**Comment by bneron** [comment]
we expected  in  February

**Comment by cschu** [comment]
Cheers, I'll keep an eye out!

**Comment by cschu** [comment]
Any news regarding this?

**Comment by bneron** [comment]
Hi
We released a new official version of macsyfinder: macsyfinder-2,0. 
This release is available on pypi, bioconda and docker.
with new or updates models,
we provided models ready to work with macsyfinder on https://github.com/macsy-models
to install these models use macsydata (ship with mascyfinder package) (check documentaion for macsyfinder and models installation https://macsyfinder.readthedocs.io/en/latest/)

Best regards

Bertrand
