### ISSUE TITLE
How can I get the modle from the macsyfinder v2.0?

### ISSUE THREAD

**Issue by lkj66666** [gem-pasteur/macsyfinder#34]
Hi, your achevement is very admirable. but i still have some problem:
1、Do I have to modify the model  myself from macsyfinder v.1 on my linux?
2、Is there any way to get the modle for macsyfinder v.2?
3、I checked the "macsydata" command. but I still don't how to use it.

**Comment by saphia** [comment]
Hi ! 

We are currently preparing a new candidate release of MacSyFinder v2 (including improved documentation for modellers), together with updated models for [protein secretion systems (TXSScan)](https://www.nature.com/articles/srep23080) and [the type IV filament super-family (TFF-SF)](https://doi.org/10.1371/journal.pbio.3000390). 
This release should be out in the next few days. 

Which models are you currently using? 
For now, you can update your favorite models following the [Documentation here](https://macsyfinder.readthedocs.io/en/latest/user_guide/new_v2.html#carrying-models-from-v1-to-v2). 
We'll gradually update all published models for the V2 version. 

Hope this helps! I'll write again here with updates on how to install models from our repo when these will be online. 

Kind regards

**Comment by saphia** [comment]
To follow up on this, we've just released models updated for V2 of MacSyFinder (for now, only TXSScan and TFF-SF - see my previous post). They should be now accessible via: 

`macsydata available`
to list available models

`macsydata install TXSS`
to install the models for protein secretion systems. 

Then:
`macsyfinder --db-type ordered_replicon 	--sequence-db myproteins.fasta --models TXSS all`
to run the MacSyFinder search of all protein secretion systems in the package TXSS on your favorite organism's genome (that is, "proteic" version of it). 

We should be able to release more updated models in the next weeks!

Best, 

Sophie

**Comment by lkj66666** [comment]
Great! Many thanks to you!!

**Comment by FranckLejzerowicz** [comment]
Hi!
I am wondering whether the models subfolder names should be renamed of there is just a help page update to do.
Indeed, in the help it is written:
```
  --models-dir MODELS_DIR
                        Specifies the path to the models if the models are not installed in the canonical place.
                        It gathers definitions (xml files) and HMM profiles arranged in a specific
                        file structure. A directory with the name of the model with at least two directories
                        	'profiles' - which contains HMM profiles for each gene components described in the systems' models
                        	'models' - which contains either the XML files of models' definitions or subdirectories
                        to organize the models in subsystems.
```
which suggest that a set of models should have two subfolders: `profiles` and `models`,
but in the latests installed one, the xml files are in a `definitions` subfolder.
```
$ ls /home/flejzerowicz/usr/miniconda3/envs/macsyfinder/share/macsyfinder/data/models/TXSS
definitions  LICENSE  metadata.yml  profiles  README.md
```
<-- no `TXSS/models` folder in there...

Also, I noted that in the previous version, this folder was names `DEF`. If I want to use the previous hmms, shall I rename the `DEF` subfolder to `definitions`, or to `models`?

I just wanted to be sure that the tool will find the info it needs, and that all its capabilities are used!
Thanks.

**Comment by saphia** [comment]
Hi, 

Yes, sorry if it was not clear (I'll try and see where potential misleading messages remain in the documentaion): in the latest version V2, the XML models should be placed in the "models" folder (they can also be placed in sub-folders within), and all HMM profiles should be placed in the folder "profiles".  

You can find the full description of the new data structure here: [https://macsyfinder.readthedocs.io/en/latest/modeler_guide/package.html](https://macsyfinder.readthedocs.io/en/latest/modeler_guide/package.html)

The macsydata tool can also help you "fix" your package in case you want to share it with colleagues, or even contribute to the macsy-models repository. See here for more details on how to share your macsy-models: [https://macsyfinder.readthedocs.io/en/latest/modeler_guide/publish_package.html](https://macsyfinder.readthedocs.io/en/latest/modeler_guide/publish_package.html)

I hope this helps! Let me know if you need more details. 

Best, 

Sophie

**Comment by lkj66666** [comment]
Hello,
MacSyFinder has been very helpful in my research, thank you very much for your work.

I was able to install MacSyFinder V2 when I installed it on another computer, but I had a problem downloading the protein models using the command `macsydata install TXSS`. Can you give me a hand? 


(macsyfinder2.0) lkj666@Cool:~/3_software/macsyfinder-master$ macsydata install TXSS
Downloading TXSS (1.0rc1).
Extracting TXSS (1.0rc1).
Traceback (most recent call last):
  File "/home/lkj666/miniconda3/envs/macsyfinder2.0/bin/macsydata", line 8, in <module>
    sys.exit(main())
  File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/macsypy/scripts/macsydata.py", line 938, in main
    parsed_args.func(parsed_args)
  File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/macsypy/scripts/macsydata.py", line 348, in do_install
    dest = config.models_dir()[0]
IndexError: list index out of range

**Comment by bneron** [comment]
can you give me the version of macsyfinder you use (macsyfinder --version)?

**Comment by lkj66666** [comment]
Macsyfinder 20220406.dev
using:
- Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37)  [GCC 9.3.0]
- NetworkX 2.5.1

MacsyFinder is distributed under the terms of the GNU General Public License (GPLv3).
See the COPYING file for details.

If you use this software please cite:
Abby SS, Néron B, Ménager H, Touchon M, Rocha EPC (2014)
MacSyFinder: A Program to Mine Genomes for Molecular Systems with an Application to CRISPR-Cas Systems.
PLoS ONE 9(10): e110726. doi:10.1371/journal.pone.0110726

and don't forget to cite models used:
macsydata cite <model>

**Comment by bneron** [comment]
I'm not 100% sure
but I think I understand what's happen
it's because you have not any directory where maxsyfinder look for the models

as workaround (waiting I fix this) I propose you install TXSS data in your home
with the following command
 macsydata install  --models_dir ~/.macsyfinder/models  TXSS
It should create the directory ~/.macsyfinder/models
install TXSS in it
and macsyfinder sould look in this directory to find TXSS
check if the installation suceed with
macsyfinder --list-models

**Comment by lkj66666** [comment]
thank you for your advice!!! 
I just tried the installation process again and was able to download and use it successfully.

**But I have another question. Can you give me some advice?
I want to customize a model (such as T3SS). I wanted to switch the order of some genes in the original model, for example I wanted to put the hrcV gene at the top of the model.**
Here's how I did it
```
i changed the original T3SS.xml as follows:

<system inter_gene_max_space="10" min_mandatory_genes_required="7" min_genes_required="7" multi_loci="1">
    <gene name="T3SS_sctV" presence="mandatory">    
    	<homologs>
            <gene name="Flg_sctV_FLG" system_ref="Flagellum"/>
        </homologs>
    </gene>
    <gene name="T3SS_sctN" presence="mandatory">       
    	<homologs>
    	    <gene name="Flg_sctN_FLG" system_ref="Flagellum"/>
    	</homologs>
    </gene>
    <gene name="T3SS_sctQ" presence="mandatory">  
        <homologs>
    	    <gene name="Flg_sctQ_FLG" system_ref="Flagellum"/>
    	</homologs>
    </gene>
    <gene name="T3SS_sctR" presence="mandatory">    
    	<homologs>
            <gene name="Flg_sctR_FLG" system_ref="Flagellum"/>
        </homologs>
    </gene>
    <gene name="T3SS_sctS" presence="mandatory">    
    	<homologs>
            <gene name="Flg_sctS_FLG" system_ref="Flagellum"/>
        </homologs>
    </gene>
    <gene name="T3SS_sctT" presence="mandatory">    
        <homologs>
    	    <gene name="Flg_sctT_FLG" system_ref="Flagellum"/>
        </homologs>
    </gene>
    <gene name="T3SS_sctU" presence="mandatory">    
        <homologs>
            <gene name="Flg_sctU_FLG" system_ref="Flagellum"/>
    	</homologs>
    </gene>
    <gene name="T3SS_sctC" presence="mandatory" exchangeable="1">        
        <homologs>
    	    <gene name="T2SS_gspD" system_ref="T2SS"/>
    	    <gene name="T4P_pilQ" system_ref="T4P"/>
    	    <gene name="Tad_rcpA" system_ref="Tad"/>
        </homologs>
    </gene>
    <gene name="T3SS_sctJ" presence="mandatory">       
        <homologs>
    	    <gene name="Flg_sctJ_FLG" system_ref="Flagellum"/>
        </homologs>
    </gene>
    <gene name="Flg_fliE" presence="forbidden" system_ref="Flagellum"/>
    <gene name="Flg_flgB" presence="forbidden" system_ref="Flagellum"/>
    <gene name="Flg_flgC" presence="forbidden" system_ref="Flagellum"/>
</system>
```
and then run:
 `macsyfinder --db-type ordered_replicon --sequence-db my_proteins.fasta --models TXSS T3SS`
but it failed. 
(ps: i have no idea how to make it though saw the documentation several times. can you give me some hints? )

**Comment by lkj66666** [comment]
Hi, 
    There are some problems with using the model. Before creating a new model, I tried the commands in the documentation as follows:
```
1.  I downloaded the original TXSS file. 
2.  macsyfinder --db-type ordered_replicon --sequence-db mygenome.fasta --models-dir TXSS --models T3SS
```
The program error is as follows:
```
Traceback (most recent call last):
  File "/home/lkj666/miniconda3/envs/macsyfinder2.0/bin/macsyfinder", line 8, in <module>
    sys.exit(main())
  File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/macsypy/scripts/macsyfinder.py", line 1048, in main
    relative_path=config.relative_path())
  File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/macsypy/registries.py", line 76, in scan_models_dir
    relative_path=relative_path)
  File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/macsypy/registries.py", line 176, in __init__
    relative_path=relative_path)
  File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/macsypy/registries.py", line 249, in _scan_profiles
    for profile in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: 'TXSS/definitions/profiles'
```
Then I copied the file to the appropriate directory and tried again, The program reported an error again as follows:
```
command used: /home/lkj666/miniconda3/envs/macsyfinder2.0/bin/macsyfinder --db-type ordered_replicon --sequence-db SC155.faa --models-dir TXSS --models T3SS
macsyfinder: "No such model definition: 'T3SS'"
```
Can you give me some advice? thanks

**Comment by bneron** [comment]
the bug is fixed in dev version.
the woraround works. close the issue
