### ISSUE TITLE
Whether it is possible to run the singularity version for the Conjugation models? 

### ISSUE THREAD

**Issue by biofuture** [gem-pasteur/macsyfinder#35]
Hello,

I would like to know whether it is possible to run the program for the conjugation model through the singularity version, if it is works.  What will be the command? Thanks.

**Comment by bneron** [comment]
The conjugation model are not yet available for the macsyfinder v2

**Comment by bneron** [comment]
Hi
We released a new official version of macsyfinder: macsyfinder-2,0.
This release is available on pypi, bioconda and docker.
with new or updates models,
we provided models ready to work with macsyfinder on https://github.com/macsy-models
to install these models use macsydata (ship with mascyfinder package) (check documentaion for macsyfinder and models installation https://macsyfinder.readthedocs.io/en/latest/)

You can use the docker image through apptainer

apptainer build --name macsyfinder-2.0 docker://://gempasteur/macsyfinder:2.0

or run it direclty as indicated in  https://hub.docker.com/r/gempasteur/macsyfinder

then use masydata to install conjscan models, ...

Best regards

Bertrand

**Comment by biofuture** [comment]
Thanks for the updates.
Regards,

Xiao-Tao Jiang, Ph.D.



Bertrand Néron ***@***.***> 于2022年9月23日周五 23:46写道：
