### ISSUE TITLE
[HELP] error when installing models

### ISSUE THREAD

**Issue by schmittel** [gem-pasteur/macsyfinder#46]
Hi,

I'm having trouble installing conjugation models for Macsyfinder v2. I'm following the instructions but am getting the errors:

```
macsydata install CONJScan_plasmids
Could not find version that satisfied 'CONJScan_plasmids'
```

```
macsydata install CONJScan
Traceback (most recent call last):
  File "/tmp/global2/code/conda_envs/conj/bin/macsydata", line 8, in <module>
    sys.exit(main())
  File "/tmp/global2/code/conda_envs/conj/lib/python3.9/site-packages/macsypy/scripts/macsydata.py", line 965, in main
    parsed_args.func(parsed_args)
  File "/tmp/global2/code/conda_envs/conj/lib/python3.9/site-packages/macsypy/scripts/macsydata.py", line 256, in do_install
    pack_name, inst_vers = parse_arch_path(args.package)
  File "/tmp/global2/code/conda_envs/conj/lib/python3.9/site-packages/macsypy/package.py", line 542, in parse_arch_path
    raise ValueError(f"{path} does not seem to be a package (a tarball).")
ValueError: CONJScan does not seem to be a package (a tarball).
```

Is there an alternative or manual way of installing these models to work with Macsyfinder?

Many thanks for your help.

**Comment by saphia** [comment]
Hi, 

We are on it! It probably comes from the fact that COnjscan is not packaged yet and therefore not available from macsydata - we'll let you know here when it is done. And yes, there is a manual way - but at this point you might want to wait for the tag at it is literally one step away from being done. 

Kind regards, 

Sophie

**Comment by schmittel** [comment]
Dear Sophie, no worries - thanks! Looking forward to the new release - this seems like a great program.

**Comment by bneron** [comment]
Hi we release a new official version of macsyfinder 
macsyfinder-2,0 this release is available on pypi, bioconda and docker.
with new or updates models, 
we provided models ready to work with macsyfinder on  https://github.com/macsy-models
to install these models use macsydata (ship with mascyfinder package) (check documentaion for macsyfinder and models installation  https://macsyfinder.readthedocs.io/en/latest/)

Best reagards

Bertrand
