### ISSUE TITLE
[HELP] .json file

### ISSUE THREAD

**Issue by cpeduzzi** [gem-pasteur/macsyfinder#47]
Hi,
First of all, I wanted to thank you for the creation of MacSyFinder tool.

I was wondering if it is still possible to generate a .json output with MacSyFinder version 2 in order to visualize the results in MacSyView ? I can't find this file format among my output files or mentioned in the latest manual ?

Many thanks for your help,

**Comment by bneron** [comment]
The output of MacSyFinder v2 totally changed from V1.
MacSyView is not able to view MacSyFinder v2 results. 
Developing MacSyViewer for the MacSyFinder v2 is not in the road map for now.
But it will depend of the interest of the community for a such tool
