### ISSUE TITLE
Error using the docker gempasteur/macsyfinder:2.0rc7

### ISSUE THREAD

**Issue by yuxiangtan** [gem-pasteur/macsyfinder#48]
**Describe the bug** **Screenshots**
![image](https://user-images.githubusercontent.com/10011271/172032412-90d823dc-939e-481d-800a-797b72f20c1a.png)

**To Reproduce**
docker run -v ${PWD}/:/home/msf -u $(id -u ${USER}):$(id -g ${USER})  gempasteur/macsyfinder:2.0rc7 macsyfinder --db-type unordered_replicon --models-dir=/home/msf/ --models  defense-finder-models 1.1.0  all --sequence-db represent_region_fasta/GCA_002872535.2_ASM287253v2_genomic_region_029.fasta -w 12

**Expected behavior**
Run the program

***OS:*** 
 - [ ] Linux

***MacSyFinder Version:***
It is impossible to run macsyfinder --version  as well.

**Comment by bneron** [comment]
```It is impossible to run macsyfinder --version as well.```
do you have the same error?

**Comment by yuxiangtan** [comment]
Yes, I tried to check the version and gave me the same error as the figure showed.

**Comment by bneron** [comment]
I cannot reproduce the error above: when I run 
```docker run -v (id -u (id -g ${USER}) gempasteur/macsyfinder:2.0rc7 macsyfinder  --version ```
I got : 
```docker run -v ${PWD}/:/home/msf -u $(id -u ${USER}):$(id -g ${USER}) gempasteur/macsyfinder:2.0rc7 macsyfinder --version
Macsyfinder 2.0rc7
using:
- Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
- NetworkX 2.8

MacsyFinder is distributed under the terms of the GNU General Public License (GPLv3).
See the COPYING file for details.

If you use this software please cite:
Abby SS, Néron B, Ménager H, Touchon M, Rocha EPC (2014)
MacSyFinder: A Program to Mine Genomes for Molecular Systems with an Application to CRISPR-Cas Systems.
PLoS ONE 9(10): e110726. doi:10.1371/journal.pone.0110726

and don't forget to cite models used:
macsydata cite <model>
```
what it is expected.
I ask to colleague to test the same command and he got exactly the same output.

**Comment by yuxiangtan** [comment]
docker run -v ${PWD}/:/home/msf -v /data/:/data/ -u $(id -u ${USER}):$(id -g ${USER})  gempasteur/macsyfinder:2.0rc7 macsyfinder --version

![image](https://user-images.githubusercontent.com/10011271/172636375-3c97a5fc-9311-4db9-8079-206f393a5ad4.png)

Is it what you need?

In fact, it can run on 2.0rc6 version.
docker run -v ${PWD}/:/home/msf -v /data/:/data/ -u $(id -u ${USER}):$(id -g ${USER})  gempasteur/macsyfinder:2.0rc6 macsyfinder --version

**Comment by bneron** [comment]
I  tested the command on gentoo and ubuntu (Impish and Jammy) and it works perfectly, I also ask to some colleagues it works also for them. 

- so could you tell me wich linux distro do you use?

- could you copy/paste  the whole trace-back (not only the end)?

**Comment by yuxiangtan** [comment]
![image](https://user-images.githubusercontent.com/10011271/172768889-b8a4c7de-8f0d-43f7-b922-e3508c06d816.png)
![image](https://user-images.githubusercontent.com/10011271/172768844-bbc665c5-1493-48c1-91bd-ff030f6455ed.png)
![image](https://user-images.githubusercontent.com/10011271/172768820-4e75af58-6660-43eb-af66-3c317cb92151.png)

#my linux
cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by bneron** [comment]
could you test without id mapping or bind/mount

**Comment by yuxiangtan** [comment]
Looks like the same.

![image](https://user-images.githubusercontent.com/10011271/173028674-e0956058-7ee1-485a-baf2-0a6f12acb04f.png)
![image](https://user-images.githubusercontent.com/10011271/173028596-b072429d-ef98-4644-8f15-0b090f5d70e2.png)
![image](https://user-images.githubusercontent.com/10011271/173028565-5de7a780-23f0-4f26-b03d-ac3ae120f807.png)
![image](https://user-images.githubusercontent.com/10011271/173028506-cbc0c439-135c-460b-86d2-c40005333add.png)

**Comment by bneron** [comment]
It's incomprehensible, I test the same line on CentOS and have no problem.
``` 
docker run gempasteur/macsyfinder:2.0rc7 macsyfinder --version

Status: Downloaded newer image for gempasteur/macsyfinder:2.0rc7
Macsyfinder 2.0rc7
using:
- Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
- NetworkX 2.8

MacsyFinder is distributed under the terms of the GNU General Public License (GPLv3).
See the COPYING file for details.

If you use this software please cite:
Abby SS, Néron B, Ménager H, Touchon M, Rocha EPC (2014)
MacSyFinder: A Program to Mine Genomes for Molecular Systems with an Application to CRISPR-Cas Systems.
PLoS ONE 9(10): e110726. doi:10.1371/journal.pone.0110726

and don't forget to cite models used:
macsydata cite <model>
```

```bash
$ cat /etc/centos-release
CentOS Linux release 8.3.2011
```

**Comment by yuxiangtan** [comment]
Honestly, I have no idea, especially when it works with 2.0rc6

I think it is OK to close this now if nobody else have the same issue.

Thank you so much!
