### ISSUE TITLE
[HELP] OSError: [Errno 39] Directory not empty when installing models

### ISSUE THREAD

**Issue by ShailNair** [gem-pasteur/macsyfinder#50]
Hi,

I have a server connection problem while installing anything from the model repository. So, I downloaded the respective model tarball  file i.e. defense-finder-models-1.1.0.tar.gz created by mdmparis (https://github.com/mdmparis/defense-finder-models)

When I run
macsydata install /home/defense-finder-models-1.1.0.tar.gz

I get the following error
Extracting defense-finder-models (1.1.0). Removing old models /tmp/tmp-macsy-cache/local/defense-finder-models/1.1.0/defense-finder-models Traceback (most recent call last): File "/home/miniconda3/envs/defensefinder/bin/macsydata", line 8, in <module> sys.exit(main()) File "/home/miniconda3/envs/defensefinder/lib/python3.7/site-packages/macsypy/scripts/macsydata.py", line 938, in main parsed_args.func(parsed_args) File "/home/miniconda3/envs/defensefinder/lib/python3.7/site-packages/macsypy/scripts/macsydata.py", line 335, in do_install cached_pack = model_index.unarchive_package(arch_path) File "/home/miniconda3/envs/defensefinder/lib/python3.7/site-packages/macsypy/package.py", line 95, in unarchive_package os.rename(unarchive_pack, dest_unarchive_path) OSError: [Errno 39] Directory not empty: '/tmp/tmp-macsy-cache/local/defense-finder-models/1.1.0/defense-finder-models/LICENSE' -> '/tmp/tmp-macsy-cache/local/defense-finder-models/1.1.0/defense-finder-models'

Things I tried:

Clearing /tmp/tmp-macsy-cache/local/defense-finder-models/1.1.0/defense-finder-models/
deleting /tmp/tmp-macsy-cache/
use macsydata install with --force/--user parameter with --target location
In all cases, the macsydata.py script decompresses the content of the tar file into the temp directory and then throws the same error.

**Comment by bneron** [comment]
I will check for the installation from local the tar.gz

**Comment by bneron** [comment]
you download defense_finder from the package (https://github.com/mdmparis/defense-finder-models/releases/download/1.1.0/defense-finder-models-1.1.0.tar.gz) which is the first link on the release page, isn't it?

instead download from the "source code" link (https://github.com/mdmparis/defense-finder-models/archive/refs/tags/1.1.0.tar.gz)
which is the last link.

**Comment by ShailNair** [comment]
Hi,
Thank you. The tarball from source link worked. However, it did there the following error

`Extracting defense-finder-models (1.1.0).
Removing old models /tmp/tmp-macsy-cache/local/defense-finder-models/1.1.0/defense-finder-models
Traceback (most recent call last):
  File "/home/miniconda3/envs/defensefinder/bin/macsydata", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/defensefinder/lib/python3.7/site-packages/macsypy/scripts/macsydata.py", line 938, in main
    parsed_args.func(parsed_args)
  File "/home/miniconda3/envs/defensefinder/lib/python3.7/site-packages/macsypy/scripts/macsydata.py", line 348, in do_install
    dest = config.models_dir()[0]
IndexError: list index out of range`


Passing the command with --upgrade --user -t successfully installed the models

`macsydata install defense-finder-models-1.1.0.tar.gz --upgrade --user -t /home/database/defensefinder/models-1.1.0/`

Thank you for the quick and helpful fix.
