### ISSUE TITLE
unrecognized argument in test run

### ISSUE THREAD

**Issue by usr2** [gem-pasteur/macsyfinder#51]
We have been trying to run the test code of macsifynder:
macsyfinder --db-type gembase --sequence-db /share/macsyfinder/sequence_data/datatest_gembase.fasta all
but we get the following error. 
macsyfinder: error: unrecognized arguments: all
Have you seen this error before?

Thanks,

**Comment by bneron** [comment]
the command line is not valid.
read the inline help `macsyfinder --help`
or the user guide  https://macsyfinder.readthedocs.io/en/latest/user_guide/index.html
