### ISSUE TITLE
[HELP] Error parsing models

### ISSUE THREAD

**Issue by alexweisberg** [gem-pasteur/macsyfinder#52]
I have used v1 of macsyfinder previously, and it has been very helpful for my research, so thank you!

I just updated to version 2 and am having some issues getting it running. I have my genome formatted in gembase format, and the input file works with the old version of macsyfinder.

I installed macsyfinder v2 using pip3, then installed the TXSScan models locally using macsydata. Those models appear to be installed and found by macsyfinder: 
$ ~/.local/bin/macsyfinder --list-models
TXSScan
        /archaea
                /Archaeal-T4P
        /bacteria
                 /diderm
                        /CONJ
                        /Flagellum
                        /MSH
                        /T1SS
                        /T2SS
                        /T3SS
                        /T4SS_typeB
                        /T4SS_typeC
                        /T4SS_typeF
                        /T4SS_typeG
                        /T4SS_typeI
                        /T4SS_typeT
                        /T4aP
                        /T4bP
                        /T5aSS
                        /T5bSS
                        /T5cSS
                        /T6SSi
                        /T6SSii
                        /T6SSiii
                        /T9SS
                        /Tad
                        /pT4SSi
                        /pT4SSt
                 /monoderm
                          /ComM

However, when I try to run macsyfinder with these models I get the following error:

$ ~/.local/bin/macsyfinder -o test_macsyfinder_TXSS --db-type gembase --sequence-db ./allgembase.faa --worker 8 --models TXSScan all
command used: /home/username/.local/bin/macsyfinder -o test_macsyfinder_TXSS --db-type gembase --sequence-db ./allgembase.faa --worker 8 --models TXSScan all

######################### Searching systems ##########################
Models Parsing
Traceback (most recent call last):
  File "/home/username/.local/bin/macsyfinder", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.7/site-packages/macsypy/scripts/macsyfinder.py", line 1074, in main
    all_systems, rejected_clusters = search_systems(config, model_registry, models_def_to_detect, logger)
  File "/home/username/.local/lib/python3.7/site-packages/macsypy/scripts/macsyfinder.py", line 491, in search_systems
    parser.parse(models_def_to_detect)
  File "/home/username/.local/lib/python3.7/site-packages/macsypy/definition_parser.py", line 87, in parse
    self._parse_genes(model, model_node)
  File "/home/username/.local/lib/python3.7/site-packages/macsypy/definition_parser.py", line 336, in _parse_genes
    ex = self._parse_exchangeable(exchangeable_node, new_gene, model)
  File "/home/username/.local/lib/python3.7/site-packages/macsypy/definition_parser.py", line 367, in _parse_exchangeable
    family_name, model_name = split_def_name(curr_model.fqn)
ValueError: too many values to unpack (expected 2)

The only output produced is a folder with a conf file and log file, and the conf file has all of the correct settings as well as the model.

Thanks!

**Comment by bneron** [comment]
can you tell me which version of macsyfinder you use ```macsyfinder --version```?

**Comment by alexweisberg** [comment]
Hi Bertrand,

~/.local/bin/macsyfinder --version
Macsyfinder 2.0rc7
using:
- Python 3.7.2 (default, Feb 9 2019, 23:04:15) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
- NetworkX 2.4

**Comment by bneron** [comment]
I fixed this issue since this release. 
The fix has not been in any release yet, but is in the master version of macsyfinder.
To install the master version in a virtualenv
```
python3 -m venv msf_env
cd msf_env
source bin/activate
mkdir src
cd src
git clone https://github.com/gem-pasteur/macsyfinder.git
cd macsyfinder
python -m pip install .
```
then to use macsyfinder

```
source msf_env/bin/activate
macsyfinder ...
macsydata ...
```

**Comment by alexweisberg** [comment]
Thank you! I updated using your instructions and the code now runs correctly and to completion. The new version is also very fast and works well. Thanks for the help!
