### ISSUE TITLE
[BUG] MacSyFinder does not deal well when a replicon has a single protein.

### ISSUE THREAD

**Issue by jeanrjc** [gem-pasteur/macsyfinder#53]
**Describe the bug**

Running macsyfinder on a properly formatted file returns `Error during sequence-db 'toto.prt' parsing. Are you sure db-type is 'gembase'?`, which is actually caused by the fact that there are multiple replicons (this is ok) in the fasta file, among which, some have a single protein (creates bug, if protein is a hit). 

**To Reproduce**
[toto.zip](https://github.com/gem-pasteur/macsyfinder/files/9281813/toto.zip) : a fake file with virb4 and 2 fake proteins on another replicon, so the bug can be reproduced with CONJScan_plasmids.

Steps to reproduce the behaviour :
1. `macsyfinder --db-type gembase --sequence-db toto.prt -m CONJScan_plasmids` 
2. See error:

```bash
Error during sequence-db 'toto.prt' parsing. Are you sure db-type is 'gembase'?
Traceback (most recent call last):
  File "/home/jean/anaconda3/envs/microbio/bin/macsyfinder", line 8, in <module>
    sys.exit(main())
  File "/home/jean/anaconda3/envs/microbio/lib/python3.8/site-packages/macsypy/scripts/macsyfinder.py", line 1074, in main
    all_systems, rejected_clusters = search_systems(config, model_registry, models_def_to_detect, logger)
  File "/home/jean/anaconda3/envs/microbio/lib/python3.8/site-packages/macsypy/scripts/macsyfinder.py", line 539, in search_systems
    systems, rejected_clusters = _search_in_ordered_replicon(hits_by_replicon, models_to_detect,
  File "/home/jean/anaconda3/envs/microbio/lib/python3.8/site-packages/macsypy/scripts/macsyfinder.py", line 564, in _search_in_ordered_replicon
    rep_db = RepliconDB(config)
  File "/home/jean/anaconda3/envs/microbio/lib/python3.8/site-packages/macsypy/database.py", line 279, in __init__
    self._fill_gembase_min_max(topo_dict, default_topology=self.cfg.replicon_topology())
  File "/home/jean/anaconda3/envs/microbio/lib/python3.8/site-packages/macsypy/database.py", line 362, in _fill_gembase_min_max
    raise MacsypyError(msg) from None
macsypy.error.MacsypyError: Error during sequence-db 'toto.prt' parsing. Are you sure db-type is 'gembase'?

```

**Expected behavior**

It should work

**Please complete the following information):**

***OS:*** 

 - [x] Linux
 - [ ] Windows
 - [ ] Mac

***MacSyFinder Version:***
```bash
$ macsyfinder --version                                                                                                                      
Macsyfinder 2.0rc7
```
**Additional context**
The error comes from this block : https://github.com/gem-pasteur/macsyfinder/blob/14077bcbaa91ae2f3c333292ddfb0a62d96d14ec/macsypy/database.py#L346-L360 where there is no check for the length of the replicon, and thus if the number of proteins in the replicon is one, it never enters the for loop L352, and thus rank is never declared. 
There should be a check for replicon with 1 single protein, that set the topology to linear and set rank to _min (or directly _max to _min)

**Comment by bneron** [comment]
There will no change of topology behind the user. (rule number 2 of zen of of python: "Explicit is better than implicit." https://peps.python.org/pep-0020/)
The user have to set --linear --circular or provide a topology file.

The error here  is raised to avoid corrupted results if user provide sequence which is a ordered replicon but set the option as gembase as with data look like below:
```
 >1E10S0A0cP00_0010 D GTG TGA 483 2027 Valid dnaA 1545 _PA0001_NP_064721.1_ PA0001 1 483 2027 
MSVELWQQCVDLLRDELPSQQFNTWIRPLQVEAEGDELRVYAPNRFVLDW
>0200S001A0c_0P1E0 D ATG TAA 2056 3159 Valid dnaN 1104 _PA0002_NP_064722.1_ PA0002 1 2056 3159 
MHFTIQREALLKPLQLVAGVVERRQTLPVLSNVLLVVEGQQLSLTGTDLE
>0000310E00S0c_1PA D ATG TGA 3169 4278 Valid recF 1110 _PA0003_NP_064723.1_ PA0003 1 3169 4278 
MSLTRVSVTAVRNLHPVTLSPSPRINILYGDNGSGKTSVLEAIHLLGLAR
>c_01000A0PS00014E D ATG TGA 4275 6695 Valid gyrB 2421 _PA0004_NP_064724.1_ PA0004 1 4275 6695 
MSENNTYDSSSIKVLKGLDAVRKRPGMYIGDTDDGTGLHHMVFEVVDNSI
>07700ES100A0cP01_ C ATG TGA 91521 94826 Valid icmF1 3306 _PA0077_NP_248767.1_ PA0077 1 91521 94826 
MQSLAEVSAPDAASVAT
```

I propose to check length of each replicon in the case of gembase.
If the large majority of them are 1 then I raised a warning.

**Comment by jeanrjc** [comment]
But the error is not relevant here, since the file is properly formatted (unlike in your example). We just needs to deal with replicon with a single protein in the code. Here the generator over replicon is exhausted with the `next` command (L. 348). We could enumerate over `replicon`, check when it's the first iteration to get `_min`, and thus rank will be correctly declared. Not sure if it handles non gembase files though. 

btw what's the topology by default, macsyfinder -h returns 0.1: 
```bash
  --replicon-topology {linear,circular}
                        The topology of the replicons
                        (this option is meaningful only if the db_type is
                        'ordered_replicon' or 'gembase'.)
                        (default: 0.1)
```

**Comment by jeanrjc** [comment]
> If the large majority of them are 1 then I raised a warning.

I'm not sure to understand what you mean. I think MF should handle replicon no matter the number of proteins in them.

**Comment by bneron** [comment]
this is why a propose to raise a warning instead an error.

**Comment by jeanrjc** [comment]
Oh, I see. yes, why not, it's easy to change !
