### ISSUE TITLE
[BUG] test_extract_concurent fail with "cannot join current thread"

### ISSUE THREAD

**Issue by nileshpatra** [gem-pasteur/macsyfinder#58]
**Describe the bug**
Testsuite failure

**To Reproduce**
Running testsuite the normal way with python3.11

There's a corresponding bug report in debian package, see [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1028774)

**Please complete the following information):**

***OS:*** 

 - [x ] Linux
 - [ ] Windows
 - [ ] Mac

***MacSyFinder Version:***

  copy/paste here the output of macsyfinder --version

2.0

**Additional context**

Looking at the code, something looks a bit odd to me in the `test_extract_concurent` and couple other tests as well for that matter. It initializes several threads but never joins them, while the test is supposed to test concurrency. Shouldn't t.join be applied for all the threads?
I've not dug much into the code but maybe patch like this is relevant?

```
--- a/tests/test_Report.py
+++ b/tests/test_Report.py
@@ -370,7 +370,7 @@
         for t in threading.enumerate():
             if t is main_thread:
                 continue
-        t.join()
+            t.join()
 
         #          gene, model,     hit_id,        hit_seq_length replicon_name, pos_hit, i_eval,  score,
         #          profile_coverage, sequence_coverage, begin_match, end_match
@@ -461,7 +461,7 @@
         for t in threading.enumerate():
             if t is main_thread:
                 continue
-        t.join()
+            t.join()
 
         #          gene, model,     hit_id,        hit_seq_length replicon_name, pos_hit, i_eval,  score,
         #          profile_coverage, sequence_coverage, begin_match, end_match
@@ -540,7 +540,7 @@
         for t in threading.enumerate():
             if t is main_thread:
                 continue
-        t.join()
+            t.join()
 
         #          gene, model,     hit_id,        hit_seq_length replicon_name, pos_hit, i_eval,  score,
         #          profile_coverage, sequence_coverage, begin_match, end_match
```
=====================================================================================================
CC: @bneron

**Comment by nileshpatra** [comment]
With the above patch, I am able to see the test failures to be not happening anymore, and the code in question does look odd in current state (that if condition in for loop is kind of useless) but I am not 100% sure if this is correct as I am not versed with the code in the rest of the codebase.

Could you please consider checking and let me know?

**Comment by emollier** [comment]
Hi,

I caught the issue on my end on a virtual machine with 2 cores, although the test suite usually passes.  Others reported more persistent test failures in [Debian Bug#1028774], common point being machines with relatively low cores count, such as 2 being more exposed than others (apparently no problem with 1 core).  Applying the patch from Nilesh resolved test failures on my end.

[Debian Bug#1028774]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1028774

Have a nice day,  :)
Étienne.

**Comment by bneron** [comment]
I merge your patch in the code.
It will be in the next version of macsyfinder which will be released  very soon
thank you to report and fix this problem
