### ISSUE TITLE
New input data type: all fastas in a folder analysed in a single macsyfinder run.

### ISSUE THREAD

**Issue by saphia** [gem-pasteur/macsyfinder#6]
Suggestions to implement this feature:
Only one type of data will be allowed for all data in fastas
- a merged fasta file will be created:
  - replicon names will be given: "basename_fasta1", "basename_fasta2"... 
  - protein ID will be given "basename_fasta1_ID1", "basename_fasta1_ID2"...
- then, data would be handled as gembase

**Comment by edusoto** [comment]
Hi Sophie,

I was wondering if this feature was already implemented in the lastest Macsyfinder release? It would be very useful a way to convert multiple fasta files into gembase format.

Thanks in advance.

Jose Eduardo

**Comment by JosephWestley** [comment]
Hello Saphia & Eduardo,

I appreciate this is an old post but thought I would ask anyway. Do either of you know how to convert multiple fasta files into a single gembase file? I am quite stuck on how to do this and wondered if anyone has a script written already that does it.

Many thanks!
Joe

**Comment by cachapuz2001** [comment]
Hi Joe,
If your fasta files are from a genome, I would suggest you use our tool PanACoTA [https://github.com/gem-pasteur/PanACoTA](https://github.com/gem-pasteur/PanACoTA ). Otherwise, I have no easy fix. 
Best regards,
Eduardo

**Comment by JosephWestley** [comment]
Hi Eduardo, 

Thank you, I will have a look at that package, I am indeed working with genomes. I ended up writing a little script that you can use to turn a folder of fasta files into a gembase file. Just need to run this then cat them all

`
#!/bin/python`
import os
os.chdir('path to your/folder with fastas')
files = os.listdir(".")

for filename in files:
    name` = filename
    shortname = filename[:15]
    print shortname
    open(filename,'r')
    with open(filename, 'r') as file :
        filedata = file.read()
    filedata = filedata.replace('WP_', shortname+'_') # Replace the target string 
    with open(shortname+'_gb.faa', 'w') as file: # Write the file out again
    file.write(filedata)
`

**Comment by cachapuz2001** [comment]
thanks. You should just be careful that the program assumes a few things in the gembase format (taking from the names the genomes and eventually the replicons).
