### ISSUE TITLE
[BUG] Macsyfinder with python subprocess kill main process on error

### ISSUE THREAD

**Issue by celliern** [gem-pasteur/macsyfinder#60]
**Describe the bug**
Running on an empty file, MacSyfinder kill all processes, including the mother process

**To Reproduce**
As a standalone bash command 

```bash
macsyfinder --db-type ordered_replicon --models TXSScan all --sequence-db empty.faa
```

Will lead to a 

```
an error occurred during Hmmer execution: command = "hmmsearch" --cpu 1 -o ...
KILL all Processes
```

Using a python subprocess :

```python
subprocess.run(
    [
        "macsyfinder",
        "--db-type",
        "ordered_replicon",
        "--models",
        "TXSScan",
        "all",
        "--sequence-db",
        "empty.faa",
    ]
)
```

will kill the python main process.

**Expected behavior**

As best, deal with empty files and have an early termination indicating the error cause.

In all case, I would expect a standard error code to be returned, that can be handled properly.

**Screenshots**

![image](https://user-images.githubusercontent.com/2683668/220751111-129f3e6f-b784-49e6-9178-33338db21d97.png)

![image](https://user-images.githubusercontent.com/2683668/220751178-eca3bd64-0e11-4953-b3c7-6f05aaeae234.png)

**Please complete the following information):**

***OS:*** 

 - [X] Linux

***MacSyFinder Version:***

Macsyfinder 2.1
using:
- Python 3.8.5 | packaged by conda-forge | (default, Jul 31 2020, 02:39:48)  [GCC 7.5.0]
- NetworkX 3.0
- Pandas 1.4.3

**Comment by mesti90** [comment]
This bug still exists in macsyfinder 2.1.6, python 3.14.2
(installed from https://hub.docker.com/layers/gempasteur/macsyfinder/2.1.6/images/sha256-fb5adda0d1d9bec95f29cd01f24b1a027b20a547682936c0d00faf307d9ff86a)
