### ISSUE TITLE
[FEAT] Enable MacSyFinder to run on zipped FASTA files

### ISSUE THREAD

**Issue by saphia** [gem-pasteur/macsyfinder#63]
HMMER is already able to run on zipped FASTA files, that would be great if MSF would be able to run both on zipped or unzipped FASTA files as input files. 

More precisely:

[x] gzip
[x] bzip2
[ ] zip

**Comment by saphia** [comment]
Yes ! Would be a great feature for gzip or bzip. I edit the initial issue.

**Comment by bneron** [comment]
the goal of this feature is to store sequences in compressed format to gain disk space and run macsyfinder analysis without to uncompress data and re-compress them after the analysis.
MacSyFinder use hmmsearch which support compressed data but only in gzip format and the file must ended with extension '.gz'
So we follow the same specifications in MSF.
We do not implement support of bzip2 o zip file as msf should have to create an uncompressed file to work with hmmsearch.
The support of gzip files has been implemented from v2.1.3
