### ISSUE TITLE
[FEAT] Should we use pyhmmer ?

### ISSUE THREAD

**Issue by jeanrjc** [gem-pasteur/macsyfinder#65]
I don't know if you've heard of pyhmmer (https://github.com/althonos/pyhmmer/), but it seems an interesting tool for macsyfinder as it allows to run hmmer and analyze its results without writing file on disk, and also they manage to improve the performance of the parallelization. 

Did you hear about it @bneron or @saphia ?

**Comment by bneron** [comment]
pyhmmer seems interesting, but not useful in our case.
I do not use several threads when I run hmmer, but I launch several hmmsearch in parallel.
Our solution scale very well even with more than 15 threads (https://peercommunityjournal.org/item/10.24072/pcjournal.250.pdf Fig6B)
So we have no interest to switch to pyhmmer

**Comment by jeanrjc** [comment]
Don't you think that it can speed up even more, since the numbers of IO is reduced ?

**Comment by althonos** [comment]
You may still be interested in using it for distribution purposes, since HMMER is your only distribution that is not in PyPI, so switching would make installing easier for your end users :+1:
