### ISSUE TITLE
[FEAT] New release to fix bugs in package manager installations

### ISSUE THREAD

**Issue by LucasPaoli** [gem-pasteur/macsyfinder#70]
**Is your feature request related to a problem? Please describe.**
The current release contains bugs that have been fixed in the main branch, e.g. https://github.com/gem-pasteur/macsyfinder/issues/69. 

**Describe the solution you'd like**
Creating a new minor release.

**Describe alternatives you've considered**
Either downloading from GitHub or fixing the code in the environment, none of which are suitable within workflow managers or SOPs.

Thank you

**Comment by jeanrjc** [comment]
Yes ! @bneron it would be great if you could find the time to release the fix. It impacts users of DefenseFinder, and also users of software using defensefinder in their pipeline (e.g. https://github.com/weisberglab/beav/issues/1).

**Comment by mmolari** [comment]
Just wanted to add my voice as well. It would be super nice to have the fix in a new release for all of the downstream pipelines. Thanks for all of the hard work!

**Comment by LudoPoire** [comment]
Hi all, glad to know I'm not the only one having trouble with profiles. 
I've had the exact same problem as in [this post](https://github.com/mdmparis/defense-finder/issues/42) has anyone found a way to fix this (without hacking the repositories.py source code) ? Or should we just wait until the next patch ? Thanks ! :)

**Comment by bneron** [comment]
this bug has been already fixed 27ee21ceb8e7100d9183b084356f791487aca4ad. just use the master version.

**Comment by LucasPaoli** [comment]
Hi @bneron, I appreciate that the master version is updated and thank you very much for the fix.

However, I just wanted to reiterate that (as mentioned also by Jean and Marco), using the master version is not a viable option for downstream softwares, pipelines or SOPs that use macsyfinder as a dependency (e.g. through pip or conda).

Thank you again!

**Comment by bneron** [comment]
I wil do a new release at the end of february but I haven't any time right now to do it.

**Comment by jeanrjc** [comment]
In the meantime, we released defensefinder (v1.2.2) with a previous version of macsyfinder that did not have the bug. We'll make another release when macsyfinder will be released.

**Comment by bneron** [comment]
I just released a new version of MacSyFinder ( https://github.com/gem-pasteur/macsyfinder/releases  2.1.4) that fix this bug
the new version is available on 
- pypi https://pypi.org/project/MacSyFinder/
- bioconda
- docker hub https://hub.docker.com/r/gempasteur/macsyfinder https://hub.docker.com/r/gempasteur/macsyfinder/tags
