### ISSUE TITLE
Generating results.macsyfinder.json file for MacSyView!

### ISSUE THREAD

**Issue by NabilAsyraf98** [gem-pasteur/macsyfinder#71]
**Describe the bug**
I am trying to generate results.macsyfinder.json file so that I can visualize the results on MacSyView but to no avail. 

**To Reproduce**
![image](https://github.com/gem-pasteur/macsyfinder/assets/89307377/a884b01a-afef-4736-aa4e-2855da0ef947)

**Expected behavior**

A results.macsyfinder.json file!
![image](https://github.com/gem-pasteur/macsyfinder/assets/89307377/cb9ef4fb-4542-418e-866a-8ec5daa4e6a9)

However, no such file exists

**Please complete the following information):**

***OS:*** 

 - [ ] Linux

***MacSyFinder Version:***

![image](https://github.com/gem-pasteur/macsyfinder/assets/89307377/f60372ab-833b-4df9-a83f-6e4d7061ffa9)

**Additional context**
Appreciate any help thanks!!!

**Comment by bneron** [comment]
MacSyFinder 2 is not compatible any more with macsyview.
