### ISSUE TITLE
[BUG]GA bit thresholds unavailable on profile T6SSiii_tssO/Q. Switch to e-value threshold (-E 0.100000)

### ISSUE THREAD

**Issue by goldenmole1** [gem-pasteur/macsyfinder#74]
**Describe the bug**
I see these errors:
GA bit thresholds unavailable on profile T6SSiii_tssO. Switch to e-value threshold (-E 0.100000)
GA bit thresholds unavailable on profile T6SSiii_tssQ. Switch to e-value threshold (-E 0.100000)

**To Reproduce**
1. The exact command lines you use '...'
#!/bin/bash

#SBATCH --mem=500G
#SBATCH -c 16
source ~/anaconda3/etc/profile.d/conda.sh
conda activate macsyfinder_env
macsyfinder --e-value-search 0.1 --sequence-db img_data_12990-26/2636416040/2636416040.genes.fna -o macsyfinder_test_2636416040 --models-dir TXSScandir/ --models TXSScan all --db-type ordered_replicon -w 16

**Expected behavior**
I ran the exact same script with hundreds of bacterial genomes that have reported T6SSs, but MacSyFinder failed to find any T6SS genes from any of these genomes.

**Screenshots**
Macsyfinder 2.1.3
using:
- Python 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
- NetworkX 3.3
- Pandas 1.4.3

MacsyFinder is distributed under the terms of the GNU General Public License (GPLv3).
See the COPYING file for details.

If you use this software please cite:
Néron, Bertrand; Denise, Rémi; Coluzzi, Charles; Touchon, Marie; Rocha, Eduardo P.C.; Abby, Sophie S. 
MacSyFinder v2: Improved modelling and search engine to identify molecular systems in genomes. 
Peer Community Journal, Volume 3 (2023), article no. e28. doi : 10.24072/pcjournal.250.
https://peercommunityjournal.org/articles/10.24072/pcjournal.250/
and don't forget to cite models used:
macsydata cite <model>

command used: /clusterfs/jgi/groups/science/homes/heejungcho/anaconda3/envs/macsyfinder_env/bin/macsyfinder --e-value-search 0.1 --sequence-db img_data_12990-26/2636416040/2636416040.genes.fna -o macsyfinder_test_2636416040 --models-dir TXSScandir/ --models TXSScan all --db-type ordered_replicon -w 16

models used: TXSScan-1.1.3

######################### Searching systems ##########################
Models Parsing
MacSyFinder's results will be stored in working_dirmacsyfinder_test_2636416040
Analysis launched on img_data_12990-26/2636416040/2636416040.genes.fna for model(s):
	- TXSScan/archaea/Archaeal-T4P
	- TXSScan/bacteria/diderm/Flagellum
	- TXSScan/bacteria/diderm/MSH
	- TXSScan/bacteria/diderm/T1SS
	- TXSScan/bacteria/diderm/T2SS
	- TXSScan/bacteria/diderm/T3SS
	- TXSScan/bacteria/diderm/T4aP
	- TXSScan/bacteria/diderm/T4bP
	- TXSScan/bacteria/diderm/T5aSS
	- TXSScan/bacteria/diderm/T5bSS
	- TXSScan/bacteria/diderm/T5cSS
	- TXSScan/bacteria/diderm/T6SSi
	- TXSScan/bacteria/diderm/T6SSii
	- TXSScan/bacteria/diderm/T6SSiii
	- TXSScan/bacteria/diderm/T9SS
	- TXSScan/bacteria/diderm/Tad
	- TXSScan/bacteria/diderm/pT4SSi
	- TXSScan/bacteria/diderm/pT4SSt
	- TXSScan/bacteria/monoderm/ComM
search gene Flg_sctJ_FLG
search gene T6SSiii_tssN
search gene Archaeal-T4P_arCOG01818
search gene Flg_sctN_FLG
search gene Archaeal-T4P_arCOG06517
search gene MSH_mshF
search gene T3SS_sctC
search gene Archaeal-T4P_arCOG03872
search gene T4SS_T_virB2
search gene Archaeal-T4P_arCOG05610
search gene T6SSi_tssB
search gene Archaeal-T4P_arCOG03360
search gene Tad_tadG
search gene T4SS_I_traO
search gene T4aP_pilY
search gene T4SS_I_traY
search gene Archaeal-T4P_arCOG02298_PP
search gene Archaeal-T4P_arCOG05057
search gene Archaeal-T4P_arCOG05119
search gene T4SS_T_virB1
search gene MSH_mshL
search gene Archaeal-T4P_arCOG07206
search gene Flg_sctR_FLG
search gene T6SSii_iglF
search gene Archaeal-T4P_arCOG04679
search gene Archaeal-T4P_arCOG02394
search gene Archaeal-T4P_arCOG05614
search gene T4bP_pilE
search gene T6SSii_vgrG
search gene T9SS_sprT
search gene T6SSii_iglG
search gene Tad_tadC
search gene T4SS_T_virB9
search gene ComM_comFC
search gene Archaeal-T4P_arCOG05166
search gene Archaeal-T4P_arCOG05608
search gene T4SS_I_traP
search gene T2SS_gspJ
search gene Archaeal-T4P_arCOG02963
search gene Archaeal-T4P_arCOG06296
search gene T6SSiii_tssR
search gene Archaeal-T4P_arCOG02964
search gene Archaeal-T4P_arCOG06291
search gene MSH_mshN
search gene T6SSi_evpJ
search gene Archaeal-T4P_arCOG07777
search gene T4SS_I_traT
search gene Archaeal-T4P_arCOG02981
search gene T6SSi_tssI
search gene Archaeal-T4P_arCOG01824
search gene Archaeal-T4P_arCOG03933
search gene Archaeal-T4P_arCOG05458
search gene Archaeal-T4P_arCOG05615
search gene Archaeal-T4P_arCOG06117
search gene T2SS_gspC
search gene T4SS_I_traW
search gene Archaeal-T4P_arCOG04652
search gene T6SSi_tssH
search gene T4SS_T_virB8
search gene T9SS_gldL_TIGR03513
search gene Archaeal-T4P_arCOG02911
search gene Archaeal-T4P_arCOG02419
search gene ComM_comGB
search gene Archaeal-T4P_arCOG05618
search gene Archaeal-T4P_arCOG08524
search gene MSH_mshG
search gene T6SSi_tssC
search gene Archaeal-T4P_arCOG06518
search gene Archaeal-T4P_arCOG02420
search gene T6SSi_tssJ
search gene Tad_tadE
search gene T6SSiii_tssF
search gene Tad_rcpB
search gene T4SS_I_traE
search gene ComM_comGC
search gene T6SSiii_tssE
search gene ComM_comK
search gene Archaeal-T4P_arCOG04148
search gene T4bP_pilQ
search gene Archaeal-T4P_arCOG03821
search gene T3SS_sctR
search gene Archaeal-T4P_arCOG05617
search gene Tad_tadA
search gene T6SSiii_tssQ
search gene T2SS_gspN
search gene T4aP_pilM
search gene T2SS_gspH
search gene MSH_mshA
search gene Archaeal-T4P_arCOG04673
search gene T6SSii_dotU
GA bit thresholds unavailable on profile T6SSiii_tssQ. Switch to e-value threshold (-E 0.100000)
search gene T4aP_pilA
search gene T4SS_I_traN
search gene T4aP_fimT
search gene T6SSii_pdpE
search gene T2SS_gspI
search gene Archaeal-T4P_arCOG00589
search gene T9SS_sprA-2_PF12118
search gene ComM_comGA
search gene Archaeal-T4P_arCOG01808
search gene Tad_rcpC
search gene T4aP_pilU
search gene ComM_comEA
search gene T4aP_pilQ
search gene T3SS_sctJ
search gene Flg_sctQ_FLG
search gene Archaeal-T4P_arCOG02916
search gene T6SSii_iglA
search gene Archaeal-T4P_arCOG05616
search gene MSH_mshK
search gene T9SS_gldM_TIGR03517
search gene T2SS_gspK
search gene T9SS_gldJ_TIGR03524
search gene T4SS_I_traR
search gene Flg_sctT_FLG
search gene T4SS_I_traQ
search gene Tad_tadF
search gene T6SSi_tssG
search gene Archaeal-T4P_arCOG10426
search gene MSH_mshI
search gene T6SSii_iglB
search gene Archaeal-T4P_arCOG05619
search gene Archaeal-T4P_arCOG07276
search gene Archaeal-T4P_arCOG01817_ATP
search gene MSH_mshE
search gene T1SS_abc
search gene T2SS_gspG
search gene T4bP_pilP
search gene Archaeal-T4P_arCOG09029
search gene Tad_flp
search gene T3SS_sctS
search gene Archaeal-T4P_arCOG01810
search gene Archaeal-T4P_arCOG04680
search gene MSH_mshJ
search gene T5aSS_PF03797
search gene T6SSii_iglE
search gene T4SS_I_traL
search gene T4aP_pilT
search gene T4SS_t4cp1
search gene T4SS_I_trbA
search gene T4bP_pilT
search gene T4aP_pilC
search gene T6SSi_tssD
search gene Archaeal-T4P_arCOG02900
search gene T9SS_porV
search gene Tad_tadB
search gene Archaeal-T4P_arCOG11939
search gene T4aP_pilX
search gene T4SS_T_virB3
search gene T4SS_I_traM
search gene MSH_mshM
search gene T6SSii_iglI
search gene T6SSiii_tssB
search gene T2SS_gspD
search gene T4SS_MOBB
search gene T6SSii_pdpB
search gene T6SSi_tssE
search gene T4aP_pilO
search gene T6SSii_iglC
search gene ComM_comX
search gene Tad_rcpA
search gene Archaeal-T4P_arCOG05987
search gene Archaeal-T4P_arCOG03871
search gene MSH_mshQ
search gene Archaeal-T4P_arCOG02425
search gene MSH_mshC
search gene Archaeal-T4P_arCOG07478
search gene Archaeal-T4P_arCOG05986
search gene Archaeal-T4P_arCOG07564
search gene ComM_comFA
search gene Archaeal-T4P_arCOG10216
search gene Flg_sctU_FLG
search gene Archaeal-T4P_arCOG01815
search gene T9SS_gldN_TIGR03523
search gene Archaeal-T4P_arCOG05613
search gene T4aP_pilP
search gene T4bP_pilB
search gene T6SSiii_tssI
search gene MSH_mshO
search gene ComM_comGF
search gene Archaeal-T4P_arCOG03870
search gene Flg_sctS_FLG
search gene ComM_comEB
search gene T2SS_gspM
search gene T4aP_pilW
search gene T6SSi_tssA
search gene T6SSiii_tssH
search gene Archaeal-T4P_arCOG02421
search gene T9SS_sprE
search gene Archaeal-T4P_arCOG01809_IM
search gene Archaeal-T4P_arCOG02416
search gene Archaeal-T4P_arCOG01812
search gene T4SS_T_virB5
search gene T1SS_mfp
search gene Flg_sctV_FLG
search gene Archaeal-T4P_arCOG11520
search gene ComM_comGG
search gene Tad_tadV
search gene Archaeal-T4P_arCOG01811
search gene T6SSii_pdpC
search gene Archaeal-T4P_arCOG03422
search gene T2SS_gspE
search gene T6SSi_tssL
search gene Tad_tadZ
search gene Archaeal-T4P_arCOG08521
search gene T4bP_pilD
search gene Archaeal-T4P_arCOG01829_Pil
search gene Archaeal-T4P_arCOG09150
search gene T3SS_sctN
search gene T4aP_pilE
search gene T6SSii_iglD
search gene T6SSiii_tssO
search gene T9SS_porU
search gene Tad_tadD
GA bit thresholds unavailable on profile T6SSiii_tssO. Switch to e-value threshold (-E 0.100000)
search gene MSH_mshI2
search gene ComM_comGE
search gene T4SS_T_virB6
search gene T6SSiii_tssP
search gene T6SSi_tssM
search gene T9SS_sprA_PF14349
search gene ComM_comC
search gene Flg_flgC
search gene ComM_comGD
search gene Archaeal-T4P_arCOG06335
search gene Archaeal-T4P_arCOG03926
search gene Archaeal-T4P_arCOG02300
search gene Archaeal-T4P_arCOG05609
search gene Archaeal-T4P_arCOG05611
search gene T6SSi_tssF
search gene T4aP_pilN
search gene T6SSiii_tssK
search gene T4SS_I_trbB
search gene T9SS_porQ
search gene Archaeal-T4P_arCOG02396
search gene Archaeal-T4P_arCOG08522
search gene Flg_fliE
search gene T4SS_I_traI
search gene T6SSiii_tssG
search gene T4aP_pilB
search gene T4bP_pilC
search gene T3SS_sctV
search gene T6SSi_tssK
search gene T2SS_gspO
search gene T4aP_pilV
search gene T2SS_gspL
search gene T4SS_T_virB11
search gene Archaeal-T4P_arCOG05612
search gene Archaeal-T4P_arCOG08085
search gene T6SSii_pdpA
search gene T2SS_gspF
search gene T6SSii_iglJ
search gene ComM_comEC
search gene Archaeal-T4P_arCOG04026
search gene T4SS_T_virB10
search gene T6SSii_pdpD
search gene T6SSii_iglH
search gene T3SS_sctU
search gene T1SS_omf
search gene T3SS_sctQ
search gene Archaeal-T4P_arCOG03511
search gene T4bP_pilA
search gene ComM_comB
search gene T4SS_I_traK
search gene MSH_mshD
search gene Archaeal-T4P_arCOG01814
search gene Archaeal-T4P_arCOG08837
search gene T3SS_sctT
search gene Archaeal-T4P_arCOG08836
search gene T4aP_pilD
search gene T4aP_pilZ
search gene Archaeal-T4P_arCOG01822
search gene MSH_mshB
search gene Flg_flgB
search gene T5bSS_translocator
search gene T9SS_gldK_TIGR03525
search gene T6SSiii_tssD
search gene T6SSiii_tssC
search gene T5cSS_PF03895
search gene MSH_mshP
search gene T4SS_virb4
search gene T9SS_sprA-3_TIGR04189

####### Writing down results in 'macsyfinder_test_2636416040' ########
No Systems found in this dataset.
END

**Please complete the following information):**

***OS:*** 

 -Linux

***MacSyFinder Version:***

Macsyfinder 2.1.3
using:
- Python 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
- NetworkX 3.3
- Pandas 1.4.3

MacsyFinder is distributed under the terms of the GNU General Public License (GPLv3).
See the COPYING file for details.

If you use this software please cite:
Néron, Bertrand; Denise, Rémi; Coluzzi, Charles; Touchon, Marie; Rocha, Eduardo P.C.; Abby, Sophie S. 
MacSyFinder v2: Improved modelling and search engine to identify molecular systems in genomes. 
Peer Community Journal, Volume 3 (2023), article no. e28. doi : 10.24072/pcjournal.250.
https://peercommunityjournal.org/articles/10.24072/pcjournal.250/
and don't forget to cite models used:
macsydata cite <model>

**Additional context**

**Comment by bneron** [comment]
can you provide us the data you work on  --sequence-db img_data_12990-26/2636416040/2636416040.genes.fna 
or if it's too big just the beginning of the file

**Comment by bneron** [comment]
The authors of the TXSScan (https://github.com/macsy-models/TXSScan) models do not provide GA-threshold for these 2 profiles, but macsyfinder have a mechanism to switch to use hmmsearch  e-value in that case. What you see in the log is just a warning not an error.

**Comment by goldenmole1** [comment]
The file looks like this: 
head img_data_12990-26/2636416040/2636416040.genes.fna
>2639022136 Ga0070510_0001 1..190(-)(Ga0070510_11) [Chitinophaga arvensicola DSM 3695]
TTACAATGGAGAGTTTGATCCTGGCTCAGGATGAACGCTAGCGGCAGGCC
TAATACATGCAAGTCGAGGGGCAGCACAGGTAGCAATACTGGGTGGCGAC
CGGCAAACGGGTGCGGAACACGTACGCAACCTTCCTTCAAGCGGGGAATA
GCCCAGAGAAATTTGGATTAATACCCCATAAGAATGTGGA

>2639022137 Ga0070510_0002 730..1494(-)(Ga0070510_11) [Chitinophaga arvensicola DSM 3695]
ATGAACAGGTACTTTATAGAAGTAGGATATAAGGGGGCGCAGTACAGCGG
GTTCCAGGTACAGGAAAATGCACATTCCGTACAGGCGGAGATTGACAGGG
CGCTGGGTATATTATTCCGGTCGCCCATAGAAACTACGGGATCCAGCAGA

**Comment by bneron** [comment]
The problem come from your input data. MacSyFinder work on proteins not on genomic data.
https://macsyfinder.readthedocs.io/en/latest/user_guide/input.html#input-dataset
